/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

import spaceinvaders.SpaceInvadersGame;
import woodyFreezeMonster.WoodyFreezeMonster;


public class App {


    public static void main(String[] args) {

        new SpaceInvadersGame();
//        new WoodyFreezeMonster();
    }

}
